Anonymous:
    handler: Anonymous

User:
    handler: User NoAuth

Operator:
    handler: Operator Password

Testing:
    handler: TestAccounts

OTP:
  handler: OneTimePassword

Certificate:
    handler: Certificate

_System:
    handler: System

