label: Enrollment

authorized_signer:
    rule1:
        # Full DN
        subject: CN=.+:estclient,.*
    rule2:
        # Full DN
        subject: CN=.+:pkiclient,.*
    rule3:
        # Full DN
        subject: CN=.+:pkiserver,.*

renewal_period: 000060

# You must set at least one of both options or remove the is_policy_loaded
# condition in the workflow definition
policy:
    allow_anon_enroll: 0
    allow_man_authen: 0
    allow_man_approv: 0
    max_active_certs: 0
    auto_revoke_existing_certs: 1
    approval_points: 1
    export_certificate: chain

profile:
    cert_profile: tls_client
    cert_subject_style: enroll

# Mapping of names to OpenXPKI profiles to be used with the
# Microsoft Certificate Template Name Ext. (1.3.6.1.4.1.311.20.2)
profile_map:
    pc-client: tls_client

eligible:
    initial:
        value: 1

    renewal:
        value: 1

    onbehalf:
       value: 1
